spring:
  kafka:
    bootstrap-servers: kafka-bars:29092
    consumer:
      group-id: notification-group
  mail:
    host: smtp.mail.ru
    port: 465
    username: ylym.land@bk.ru
    password: VwzCHoVe1sjBPjEni37q
    protocol: smtps
    properties:
      mail:
        smtps:
          auth: true


notif:
  kafka:
    server: kafka-bars:29092

telegram:
  bot:
    token: 7768674488:AAHSURPudjTNkeZ_AMup5i16Ix9uOQW26oM
  chat:
    id: "781688675"

log:
  kafka:
    topic: "logs-topic"



