
services:
  # === Kafka & ZooKeeper ===
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    container_name: zookeeper-bars
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - kafka-network

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: kafka-bars
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT_INTERNAL:PLAINTEXT,PLAINTEXT_EXTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT_INTERNAL://kafka:29092,PLAINTEXT_EXTERNAL://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT_INTERNAL://0.0.0.0:29092,PLAINTEXT_EXTERNAL://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - kafka-network

  # === notification-service ===
  notification-service:
    build: ./notification-service
    container_name: notification-service
    ports:
      - "8080:8080"
    depends_on:
      - kafka
    networks:
      - kafka-network

  # === log-service ===
  log-service:
    build: ./log-service
    container_name: log-service
    ports:
      - "8082:8082"
    depends_on:
      - kafka
      - elasticsearch
    networks:
      - kafka-network
      - elastic-network

  # === Elasticsearch для хранения логов ===
  elasticsearch:
    image: docker.io/elasticsearch:8.11.3
    container_name: elasticsearch
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
      ELASTIC_PASSWORD: "admin"
    ports:
      - "9200:9200"
    networks:
      - elastic-network
    volumes:
      - esdata:/usr/share/elasticsearch/data

  # === Grafana для визуализации логов ===
  grafana:
    image: kamenskiyyyy/grafana-russian:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_USERS_ALLOW_SIGN_UP: "false"
    networks:
      - elastic-network

# === Сети ===
networks:
  kafka-network:
    driver: bridge
  elastic-network:
    driver: bridge

# === Вolumes ===
volumes:
  esdata:
    driver: local
  grafana-storage:
    driver: local